# SpringDoc Configuration
springdoc.swagger-ui.url=/api/openapi.json
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

# Port Configuration
server.port=8080
